mun_kirjat_main_frontpage:
    defaults: { _controller: MunKirjatMainBundle:Default:index }
    pattern: "/"

mun_kirjat_main_about:
    pattern: "/about"
    defaults: { _controller: MunKirjatMainBundle:Default:about }

mun_kirjat_main_template:
    pattern: "/tpl"
    defaults: { _controller: MunKirjatMainBundle:Default:template }


