services:
    munkirjat_main.menu.primary_menu.builder:
        class: MunKirjat\MainBundle\Menu\PrimaryMenuBuilder
        arguments: ["@knp_menu.factory", "@security.context", "@translator"]

    munkirjat_main.menu.primary_menu:
        class: Knp\Menu\MenuItem
        factory_service: munkirjat_main.menu.primary_menu.builder
        factory_method: createMenu
        arguments: ["@request"]
        scope: request
        tags:
            - {name: knp_menu.menu, alias: primary_menu }

    ajax.listener:
          class: MunKirjat\MainBundle\Event\AjaxAuthenticationListener
          tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }

    munkirjar_main.type.custom_tag:
        class: MunKirjat\MainBundle\Form\Type\TagType
        arguments: ["@fpn_tag.tag_manager"]
        tags:
            - { name: form.type, alias: custom_tag }