jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path:                     /login
                check_path:                     /login_check
                always_use_default_target_path: true
                default_target_path:            /login_success
                use_referer:                    false
                failure_path:                   /login_failure

            logout:
                target: /
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/allowed-actions$,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/author$,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/author$,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/new-token/new-author$,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/genre$,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/search,                      roles: IS_AUTHENTICATED_ANONYMOUSLY}

        - { path: ^/logout,                     roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/author,                     roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/genre,                      roles: IS_AUTHENTICATED_FULLY}
