---

php_apt_repo:   'ppa:ondrej/php5'

webserver_user:   "vagrant"
phpfpm_listen:    "localhost:9000"

php_apt_packages:
  - php5-cli
  - php5-fpm
  - php5-intl
  - php5-mysql
  - php5-mcrypt
  - php5-gd
  - php5-curl
  - php5-memcache