---

- name: Install repositories
  apt_repository:   repo='{{ item }}'
                    state=present
                    update_cache=yes
  with_items:
  - '{{ php_apt_repo }}'
  tags: php

- name: Install php packages
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - '{{ php_apt_packages }}'
  tags: php


- name: Configure php5-fpm
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
            section=www
            option='{{ item.option }}'
            value='{{ item.value }}'
            backup=yes
  with_items:
    - { option: 'user', value: '{{ webserver_user }}' }
    - { option: 'group', value: '{{ webserver_user }}' }
    - { option: 'listen', value: '{{ phpfpm_listen }}' }
    - { option: 'listen.owner', value: '{{ webserver_user }}' }
    - { option: 'listen.group', value: '{{ webserver_user }}' }
  tags: php

- name: Ensure running
  service: name=php5-fpm
           state=started
  tags: php