munkirjat_book_test:
    pattern: "/test"
    defaults: { _controller: MunKirjatBookBundle:Default:index }

munkirjat_book_view:
    locales: {fi: "/kirja/{id}", en: "/book/{id}" }
    defaults: { _controller: MunKirjatBookBundle:Default:view }
    requirements: { _method: get }

munkirjat_author_new:
    pattern: /author/new
    defaults: { _controller: MunKirjatBookBundle:Author:new }
    requirements: { _method: get }

munkirjat_author_create:
    pattern: /author
    defaults: { _controller: MunKirjatBookBundle:Author:create }
    requirements: { _method: post }

munkirjat_statistics_statistics:
    pattern: /statistics
    defaults: { _controller: MunKirjatBookBundle:Statistics:statistics }
    requirements: { _method: get}

