jme_sf2_generic_default:
    pattern: /
    defaults: { _controller: JmeSf2GenericBundle:Default:index }

jme_sf2_generic_frontpage:
    locales: {en: "/en", fi: "/fi"}
    defaults: { _controller: JmeSf2GenericBundle:Default:index }